version: '2'

services:
  zookeeper-cb:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-cb
    hostname: zookeeper-cb
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka-cb:
    image: bitnami/kafka:latest
    container_name: kafka-cb
    hostname: kafka-cb
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cb:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: LISTENER_DOCKER://kafka-cb:29092,LISTENER_OUT://kafka-cb:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka-cb:29092,LISTENER_OUT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
